### ISSUE TITLE
[Question] What tool did you use to generate the code from the schema?

### ISSUE THREAD

**Issue by msmcconnell** [JensKlimke/odrparser#2]
As the question says, I was wondering what tool you used to auto-generate the code from the schema file?

**Comment by zwkcoding** [comment]
When you explore the code,  I found this :

```
// Generated with xsd2cpp (https://github.com/JensKlimke/xsd2cpp) on 2020-08-13
https://github.com/JensKlimke/xsd2cp
```

But this repo doesn't exist. 

@JensKlimke  Could you reopen this repo, please ?  I  want to use this tool for OpenDRIVE 1.6.

**Comment by JensKlimke** [comment]
Sorry, for answering so late. Unfortunately, the projects are not well maintained by myself.

The xsd2cpp project is a quick&dirty implementation for parsing exactly the ODR 1.5 definition. It does not implement the full xsd standard and is not well documented. I will reopen the project, but the whole thing is not working out of the box with ODR 1.6 (I tested it a few months ago).

You could try to implement the missing features (don't know how much work this would be) or you could check the changes from 1.5 to 1.6 and implement it in a fork of this project manually.

I would really like to support and provide more generic solutions, but currently I have no time at all to do this.

**Comment by zwkcoding** [comment]
> Sorry, for answering so late. Unfortunately, the projects are not well maintained by myself.
> 
> The xsd2cpp project is a quick&dirty implementation for parsing exactly the ODR 1.5 definition. It does not implement the full xsd standard and is not well documented. I will reopen the project, but the whole thing is not working out of the box with ODR 1.6 (I tested it a few months ago).
> 
> You could try to implement the missing features (don't know how much work this would be) or you could check the changes from 1.5 to 1.6 and implement it in a fork of this project manually.
> 
> I would really like to support and provide more generic solutions, but currently I have no time at all to do this.

This tool is OK：  https://www.codesynthesis.com/products/xsd/.
I searched on github and found xsd2cpp for xdr1.6 using this tool,   for your referance @JensKlimke :[  Brucknem/OpenDRIVE ](https://github.com/Brucknem/OpenDRIVE)
